feat: add comments
AlexMarkGIT/java-explore-with-me pull request #3
Opened 2024-05-22 07:02 UTC by AlexMarkGIT

2024-05-22 18:29 UTC, afomkina requested changes

2024-05-22 18:29 UTC, afomkina commented on README.md
Распиши, пожалуйста, README более подробно:
* описание проекта
* основные endpoint'ы
* описание доп фичи

2024-05-22 18:29 UTC, afomkina commented on main/src/main/java/ru/practicum/comment/CommentPrivateController.java
> +        System.out.println("\n");
Нужно удалить печать в консоль, так как у нас есть логирование в проекте. Если печать в консоль добавлена для дебага, можно использовать логирование уровня .debug вместо

2024-05-22 18:29 UTC, afomkina commented on main/src/main/java/ru/practicum/comment/dto/CommentDto.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", shape = JsonFormat.Shape.STRING)
Паттерн лучше вынести в публичную константу в отдельный утильный класс и переиспользовать по всему проекту

2024-05-22 18:29 UTC, afomkina commented on main/src/main/resources/schema.sql
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2024-05-22 18:29 UTC, afomkina commented on main/src/main/java/ru/practicum/comment/model/CommentMapper.java
> +    CommentPublicDto toPublicDto(Comment comment);
 Похоже, что метод нигде не используется

2024-05-22 18:29 UTC, afomkina commented on main/src/main/java/ru/practicum/comment/CommentAdminController.java
Контроллеры, сервисы и репозиторий лучше разнести по разным пакетам

2024-05-23 00:17 UTC, AlexMarkGIT commented on README.md
Сделано!

2024-05-23 00:18 UTC, AlexMarkGIT commented on main/src/main/java/ru/practicum/comment/CommentPrivateController.java
> +        System.out.println("\n");
Сделано! Спасибо, что заметила. Хотел что-то быстро исправить в итоге даже не понадобилось и забыл)

2024-05-23 00:53 UTC, AlexMarkGIT commented on main/src/main/java/ru/practicum/comment/dto/CommentDto.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", shape = JsonFormat.Shape.STRING)
Сделано!

2024-05-23 01:14 UTC, AlexMarkGIT commented on main/src/main/resources/schema.sql
Спасибо за ссылку!) Если не критично, оставлю, как есть, т.к. уже финальный этап. +В ближайшем будущем изучу подробнее

2024-05-23 01:23 UTC, AlexMarkGIT commented on main/src/main/java/ru/practicum/comment/model/CommentMapper.java
> +    CommentPublicDto toPublicDto(Comment comment);
Насколько я понял работу Mapstruct, метод toPublicDto() впоследствии используется мапстрактом при генерации имплементации маппера toPublicDtoList(), т.е. он итерируется по коллекции методом toPublicDto(). Это будет видно в идее, если собрать весь проект...Либо я чего-то не знаю))

2024-05-23 01:31 UTC, AlexMarkGIT commented on main/src/main/java/ru/practicum/comment/CommentAdminController.java
На протяжении курса там предлагалось несколько шаблонов разбивки по пакетам в разных проектах, в том числе и такой, как у меня. Согласен, что на наверно на реальном большом проекте это точно необходимо, но здесь такой вариант нахожу более удобным с меньшим количеством вкладок. Тк продолжения проекта не будет, с твоего позволения, оставлю без изменений.

2024-05-23 15:11 UTC, afomkina commented on main/src/main/java/ru/practicum/comment/model/CommentMapper.java
> +    CommentPublicDto toPublicDto(Comment comment);
Логично, молодец, что разобрался!

2024-05-23 15:11 UTC, afomkina approved these changes

2024-05-23 15:22 UTC, merged